server:
  port: 8081

spring:
  application:
    name: blog_body

  datasource:
    url: jdbc:mysql://*********:3306/myblog?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: *******
    password: *******
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 500000
      maximum-pool-size: 20
      minimum-idle: 3


  redis:
    host: *********
    port: 6379
    password: *********
    database: 0
    timeout: 500000ms

  mvc:
    static-path-pattern: /static/**

  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 2MB

  rabbitmq:
    host: ********
    port: 5672
    username: **********
    password: **********
    virtual-host: /
    listener:
      simple:
        #消费者最小数量
        concurrency: 1
        #消费者最大数量
        max-concurrency: 5
        #限制消费者每次只能处理N条信息
        prefetch: 1
        #被拒绝后是否重新进入队列
        auto-startup: true

  mail:
    host: smtp.qq.com
    username: **********
    password: **********

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: ms_

qiniu:
  accessKey: "************"
  accessSecretKey: "****************"
